videoclub/apps/usuario/urls.py
from django.conf.urls import patterns, url
from apps.usuario.views import Registro, RegistroOk

urlpatterns= patterns('',
	url(r'^registrar/', Registro.as_view(), name='registrar'),
	url(r'^usrValido/', RegistroOk.as_view(), name='registroOk'),
	
	
)

videoclub/videoclub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .views import login_view

urlpatterns = [
  	url(r'^$', login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administracion/', include('apps.administracion.urls', namespace='administracion')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^pelicula/', include('apps.pelicula.urls', namespace='pelicula')),
    url(r'^videoclub/', include('apps.pagVideoclub.urls', namespace='pagVideoclub')),  
    url(r'^reset/reseteoContraseña', password_reset, {'template_name':'resetearContraseña/reseteoPwdForm.html','email_template_name':'resetearContraseña/reseteoPwdEmail.html'}, name='password_reset'),
   	url(r'^reset/reseteoAvisoContraseña', password_reset_done, {'template_name':'resetearContraseña/reseteoPwdAviso.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetearContraseña/reseteoPwdConfir.html'}, name='password_reset_confirm'),
	url(r'^reset/reseteo', password_reset_complete, {'template_name':'resetearContraseña/reseteoPwd.html'}, name='password_reset_complete'),

]

videoclub/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">	
	<head>
        <title>VideoClub DAW</title>
        <meta charset="utf-8">
   		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
   		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
 	    <meta name="description" content="Practica Web">
   	 	<meta name="author" content="Maria Ramirez y Nuria Gutierrez">
        
   		<!-- Custom styles -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   		<link rel="stylesheet" href="{% static 'css/estilo1.css' %}">
	  
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
		<!-- Scrip: Inicio de Sesión -->

    </head>

<body>
    <div class="container">
    	<div class="center jumbotron text-center" style="background-color: #F1D28A" > 
    		<h1 style="font-family:Chalkduster">DAW Movie</h1> 
    		<p style="font-family:Bradley Hand">Accede a tu VideoClub de manera gratuita, sólo tienes que Iniciar sesión o Registrarte.</p> 
    		<p style="font-family:Chalkboard">
    		   <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal1">Iniciar Sesión</button>
    		   	<div class="modal fade" id="myModal1" role="dialog">
			 	   <div class="modal-dialog">
				 	 <!-- Modal content-->
						<div class="modal-content">
							 <div class="modal-header">
							  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
         						 <span aria-hidden="true">&times;</span>
     						  </button>
							  <img class="mb-4" src="http://unitastender.hu/assets/img/people.png" alt="" width="70" height="70">
							  <h5 class="h3 mb-3 font-weight-normal" style="font-family:Bradley Hand">Inicie Sesión</h5>
							 
							 </div>
							  <div class="modal-body">
                         	   <form role="form" method="post" id='form_login'>
                             		{% csrf_token %}
                    	   			 <div class="form-group text-center">
                                 		<label>Usuario:</label>
                               	 	   	<input class="form-control" type="text" name="username" value="" id="username" />
                           	 		 </div>
                         			 <div class="form-group text-center">
                            			<label>Contraseña:</label>
                             		    <input class="form-control" type="password" name="password" value="" id="password" />
                             		 </div>                 
                             		 <div class="form-check">
   										 <input type="checkbox" class="form-check-input" id="checkme" />
   										 <label class="form-check-label" for="checkme">Recuérdame</label>
  									 </div>
  									 <div class="form-group">
   										 <a href="{% url 'password_reset' %}"><h5>Recuperar contraseña</h5></a>
  									 </div>                  
                              	 	 <button class="btn btn-lg btn-success btn-block" type="submit" name="login">Login</button>                         
                            	</form>
                        	</div>
		   				</div>		
		 		     </div>	
		    	 </div>
		    </p>
		    <p style="font-family:Chalkboard">
    		   <a href="{% url 'usuario:registrar' %}"><button type="button" class="btn btn-info btn-lg">Registrar</button></a>
    		</p>
  		</div>
    </div>
</body>

    
 