videoclub/apps/administracion/urls.py
from django.conf.urls import patterns, url 
from apps.administracion.views import Administracion, PeliculaList, PeliculaDetail, PeliculaCreation, PeliculaUpdate, PeliculaDelete, UsuarioList, UsuarioDetail, UsuarioCreation, UsuarioUpdate, UsuarioDelete



urlpatterns= patterns('',
	url(r'^$', Administracion.as_view(),name='admin'),
   
    url(r'^pelicula/$', PeliculaList.as_view(), name='list'),
    url(r'^pelicula/(?P<pk>\d+)$', PeliculaDetail.as_view(), name='detail'),
    url(r'^pelicula/nuevo$', PeliculaCreation.as_view(), name='new'),
    url(r'^pelicula/editar/(?P<pk>\d+)$', PeliculaUpdate.as_view(), name='edit'),
    url(r'^pelicula/borrar/(?P<pk>\d+)$', PeliculaDelete.as_view(), name='delete'),  
    
    url(r'^usr/$', UsuarioList.as_view(), name='listUsr'),
    url(r'^usr/(?P<pk>\d+)$', UsuarioDetail.as_view(), name='detailUsr'),
    url(r'^usr/nuevo$', UsuarioCreation.as_view(), name='newUsr'),
    url(r'^usr/editar/(?P<pk>\d+)$', UsuarioUpdate.as_view(), name='editUsr'),
    url(r'^usr/borrar/(?P<pk>\d+)$', UsuarioDelete.as_view(), name='deleteUsr'),
)


    

videoclub/apps/pagVideoclub/urls.py
from django.conf.urls import patterns, url
from .views import Logout, peliculas, search

urlpatterns= patterns('',
	url(r'^$', peliculas, name='videoclub'),
	url(r'^search', search, name='search'),
	url(r'^salir', Logout.as_view(), name='logout'),
	
)

videoclub/apps/pelicula/urls.py
from django.conf.urls import patterns, url 
from apps.pelicula.views import pelicula_id, pelicula_filtro, pelicula_list


urlpatterns= patterns('',
	url(r'^listadoPeliculas/$', pelicula_list, name='pelicula_list'),
  	url(r'^(?P<etiqueta>[-\w]+)/$', pelicula_filtro, name='pelicula_filtro'),
    url(r'^pelicula/(?P<pk>[0-9]+)/$', pelicula_id, name='pelicula_id'),
    
)


    

videoclub/videoclub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .views import login_view

urlpatterns = [
  	url(r'^$', login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administracion/', include('apps.administracion.urls', namespace='administracion')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^pelicula/', include('apps.pelicula.urls', namespace='pelicula')),
    url(r'^videoclub/', include('apps.pagVideoclub.urls', namespace='pagVideoclub')),  
    url(r'^reset/reseteoContraseña', password_reset, {'template_name':'resetearContraseña/reseteoPwdForm.html','email_template_name':'resetearContraseña/reseteoPwdEmail.html'}, name='password_reset'),
   	url(r'^reset/reseteoAvisoContraseña', password_reset_done, {'template_name':'resetearContraseña/reseteoPwdAviso.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetearContraseña/reseteoPwdConfir.html'}, name='password_reset_confirm'),
	url(r'^reset/reseteo', password_reset_complete, {'template_name':'resetearContraseña/reseteoPwd.html'}, name='password_reset_complete'),

]

videoclub/apps/pagVideoclub/models.py
from django.db import models

# Create your models here.

videoclub/apps/pagVideoclub/views.py
from django.shortcuts import render,redirect
from django.views.generic.base import TemplateView, RedirectView
from django.contrib.auth.views import logout
from apps.pelicula.forms import Pelicula
from apps.pelicula.views import pelicula_id, pelicula_filtro, mediaValoracion

# Create your views here.
class Logout(RedirectView):
    pattern_name = 'login'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(Logout, self).get(request, *args, **kwargs)
 
def peliculas(request):
	etiqueta=['Estrenos','Comedia','Drama', 'Infantil']
	peliculas=[]
	lista=[]
	#Lista de sublistas de ultimas 4 películas para cada etiqueta
	for etiq in etiqueta:
		lista.append(Pelicula.objects.filter(etiqueta=etiq)[:4])
	
	#Creamos una lista, que contenga 16 películas para que se muestren en videoclub.html
	for x in lista:
		for i in x:
			peliculas.append(i)
			
	contexto = {'etiquetas': etiqueta, 'peliculas': peliculas}
	return render(request, 'pagVideoclub/videoclub.html', contexto)
	
def search(request):
	titulo = request.GET.get('titulo')
	try:	
		pelicula = Pelicula.objects.get(titulo=titulo)
		if request.method == 'POST':
			voto = request.POST['valoracion']
			valoracionFinal = mediaValoracion(pelicula.valoracion, int(voto))
			pelicula.valoracion = valoracionFinal
			pelicula.save()
			return render(request, 'pelicula/pelicula_id.html', {'pelicula': pelicula})
		else:
			return render(request,'pelicula/pelicula_id.html', {'pelicula': pelicula})
	except: 
		return render(request,'pagVideoclub/errorBusqueda.html')

videoclub/videoclub/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect

def login_view(request):
	if request.method == 'POST':
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('pagVideoclub:videoclub')
		else:
			print ("Login error " + username + " " + password)
			return render(request,'index.html')
	else:
		return render(request,'index.html')

videoclub/templates/pagVideoclub/errorBusqueda.html
{% extends 'base/base1.html' %}


{% block content %}
<div class="container text-center">
	<br>
	<br>
	<h2 style="font-family:Marker Felt; color:#D4E6F1">Lo sentimos, no se ha podido encontrar esta película</h2>
	
	<div class="col-sm-1.5">
			<br>
			<br>
			<p><a class="btn btn-warning btn-lg" href="{% url 'pagVideoclub:videoclub' %}" role="button">Atrás</a></p>
	</div>
</div>
{% endblock %}

videoclub/templates/pagVideoclub/videoclub.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VIDEOCLUB</title>

    <!-- Bootstrap core CSS -->
      
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">


    <!-- Custom styles -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   	<link rel="stylesheet" href="{% static 'css/estilo2.css' %}">
   	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
  
   <div class="container-fluid">
	 <nav class="navbar navbar-inverse">
	   <div class="container-fluid">
	    <ul class="nav navbar-nav">
	       <li class="navbar-left"><a data-toggle="modal" data-target="#myModal1">Ayuda</a></li>      
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	      {% if  user.get_username == "admin"  %}
		  <li><button type="button" class="btn btn-default navbar-btn"><a href="{% url 'administracion:admin' %}">Administración</a></button></li>
		  {% endif %}
	      <li><a><span class="glyphicon glyphicon-user"></span> Hola, <strong>{{ user.get_username }}</strong></a></li>
	      <li><a href="{% url 'pagVideoclub:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Cerrar Sesión</a></li>
	    </ul>
	  </div>
	</nav>
	<div class="modal fade" class="modal-dialog" id="myModal1" role="dialog">
	  <div class="modal-dialog">
	     <div class="modal-content text-center" ">
	 		 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			 <span aria-hidden="true">&times;</span></button>
			 <p><h4 style="color:#1ABC9C">¿Necesitas ayuda?</h4></p>
			 <p style="font-size:12pt">Para cualquier consulta escribe a <strong>practicanym@gmail.com</strong>, ¡estaremos encantadas de ayudarte!</p>						  
			 
		</div>
	  </div>
    </div>
   </div>

	
	<div class="container">
	  <div class="row" align="center">
        <div class="col-md-8" align="right"><p  style="font-size:60pt; font-family:Chalkduster; color:black">Daw Movie</p></p></div>
        <div class="col-md-4"  align="left"><img class="alignright" src="https://icon-icons.com/icons2/810/PNG/512/cinema_popcorn_icon-icons.com_66128.png" width="100px"></div>
      </div>
	  <div class="row" align="center">
		<div class="col-md-12">
		<form id="searchform" action="{% url 'pagVideoclub:search' %}" method="get">
		   <ul class="input-group col-md-6">
		  	 <input class="form-control" id="searchbox" name="titulo" type="text" placeholder="Buscar" aria-label="Buscar">
		  	 <span class="input-group-btn"><button class="btn btn-info btn-md" type="searchbutton"><i class="glyphicon glyphicon-search"></i></button></span>
		   </ul>
		</form>
	   </div>
	</div>
	</div>
  

	<div class="container-fluid">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
  	<!-- Indicators -->
  		<ol class="carousel-indicators">
    		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    		<li data-target="#myCarousel" data-slide-to="1"></li>
    		<li data-target="#myCarousel" data-slide-to="2"></li>
			<li data-target="#myCarousel" data-slide-to="3"></li>
			<li data-target="#myCarousel" data-slide-to="4"></li>
  		</ol>

  		<!-- Wrapper for slides -->
  		<div class="carousel-inner">
  			<div class="item active">
      			<img src="https://i.pinimg.com/originals/66/24/96/6624960f0062bd8b8845037c6776277c.jpg" width="100" height="800">
    		</div>
    		<div class="item">
      			<img src="http://elpalomitron.com/wp-content/uploads/2015/04/ma1.png" width="100" height="800">
   			</div>

    		<div class="item">
      			<img src="http://3.bp.blogspot.com/-R4zvChg2z5Y/VjIU3IeDzJI/AAAAAAAAHzA/1XB3osIocwE/s1600/MGN_CARTEL_HORIZONTAL_ONLINE_AF-2.jpg" width="100" height="800">
    		</div>
		
			<div class="item">
      			<img src="http://thecitizen.es/wp-content/uploads/2018/03/perfectos.jpg" width="100" height="800">
    		</div>
    		<div class="item">
      			<img src="http://www.dvd-forum.at/img/uploaded/hr_The_Hobbit%20_The_Desolation_of_Smaug_28.jpg" width="100" height="800">
    		</div>
  		</div>

 	 <!-- Left and right controls -->
  		<a class="left carousel-control" href="#myCarousel" data-slide="prev">
    		<span class="glyphicon glyphicon-chevron-left"></span>
    		<span class="sr-only">Previous</span>
  		</a>
  		<a class="right carousel-control" href="#myCarousel" data-slide="next">
    		<span class="glyphicon glyphicon-chevron-right"></span>
    		<span class="sr-only">Next</span>
  		</a>
	</div>
	</div>
	
	<div class="container-fluid">
		<div class="row">
		{% for etiqueta in etiquetas %}	
			<div class="col-md-10 col-md-offset-1">
			<br>
			<p><span class="border-bottom" style="font-family:fantasy; font-size:36px; color:#FBFCFC"><strong>{{ etiqueta }}</strong></span>
			<a href="{% url 'pelicula:pelicula_filtro' etiqueta=etiqueta %}"><span style="float:right; font-family:Calibri (Cuerpo); font-size:16px; color:#D4AC0D">Ver más</span></a></p>
				{% for pelicula in peliculas %}
					{% if pelicula.etiqueta == etiqueta %}
					<div class="col-md-3 text-center">
						<div class="pelicula">
						<img src="{{ pelicula.portada }}" class="img-responsive center-block"  width="220">
            			<h5><a href="{% url 'pelicula:pelicula_id' pk=pelicula.pk %}"><p style="font-family:Calibri (Cuerpo); font-size:16px; color:#85C1E9">{{ pelicula.titulo }}</p></a></h5>
                        
	  		 			
					  </div>
      			   </div>
      			 {% endif %} 
      		{% endfor %}
      		</div>			 
		{% endfor %}
   	   </div>
   	 </div>
   	 <div class="col-sm-4 col-sm-offset-5">
		<p><a class="btn btn-warning btn-lg" href="{% url 'pelicula:pelicula_list' %}" role="button">Ver todas las películas</a></p>
	 </div>	
	 <br />
	 <br />	
	<hr aline="center" size="4" width="600" color="#95A5A6"/>
		<div class="container text-center">
			<span style="font-family:Calibri (Cuerpo); font-size:14px; color:#000">Universidad Politécnica de Madrid
			<p>2017-2018</p></span>
		</div>	
    </body>
</html>