videoclub/apps/administracion/urls.py
from django.conf.urls import patterns, url 
from apps.administracion.views import Administracion, PeliculaList, PeliculaDetail, PeliculaCreation, PeliculaUpdate, PeliculaDelete, UsuarioList, UsuarioDetail, UsuarioCreation, UsuarioUpdate, UsuarioDelete



urlpatterns= patterns('',
	url(r'^$', Administracion.as_view(),name='admin'),
   
    url(r'^pelicula/$', PeliculaList.as_view(), name='list'),
    url(r'^pelicula/(?P<pk>\d+)$', PeliculaDetail.as_view(), name='detail'),
    url(r'^pelicula/nuevo$', PeliculaCreation.as_view(), name='new'),
    url(r'^pelicula/editar/(?P<pk>\d+)$', PeliculaUpdate.as_view(), name='edit'),
    url(r'^pelicula/borrar/(?P<pk>\d+)$', PeliculaDelete.as_view(), name='delete'),  
    
    url(r'^usr/$', UsuarioList.as_view(), name='listUsr'),
    url(r'^usr/(?P<pk>\d+)$', UsuarioDetail.as_view(), name='detailUsr'),
    url(r'^usr/nuevo$', UsuarioCreation.as_view(), name='newUsr'),
    url(r'^usr/editar/(?P<pk>\d+)$', UsuarioUpdate.as_view(), name='editUsr'),
    url(r'^usr/borrar/(?P<pk>\d+)$', UsuarioDelete.as_view(), name='deleteUsr'),
)


    

videoclub/apps/pelicula/urls.py
from django.conf.urls import patterns, url 
from apps.pelicula.views import pelicula_id, pelicula_filtro, pelicula_list


urlpatterns= patterns('',
	url(r'^listadoPeliculas/$', pelicula_list, name='pelicula_list'),
  	url(r'^(?P<etiqueta>[-\w]+)/$', pelicula_filtro, name='pelicula_filtro'),
    url(r'^pelicula/(?P<pk>[0-9]+)/$', pelicula_id, name='pelicula_id'),
    
)


    

videoclub/videoclub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .views import login_view

urlpatterns = [
  	url(r'^$', login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administracion/', include('apps.administracion.urls', namespace='administracion')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^pelicula/', include('apps.pelicula.urls', namespace='pelicula')),
    url(r'^videoclub/', include('apps.pagVideoclub.urls', namespace='pagVideoclub')),  
    url(r'^reset/reseteoContraseña', password_reset, {'template_name':'resetearContraseña/reseteoPwdForm.html','email_template_name':'resetearContraseña/reseteoPwdEmail.html'}, name='password_reset'),
   	url(r'^reset/reseteoAvisoContraseña', password_reset_done, {'template_name':'resetearContraseña/reseteoPwdAviso.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetearContraseña/reseteoPwdConfir.html'}, name='password_reset_confirm'),
	url(r'^reset/reseteo', password_reset_complete, {'template_name':'resetearContraseña/reseteoPwd.html'}, name='password_reset_complete'),

]

videoclub/apps/pelicula/models.py
from django.db import models
from django.contrib import admin
# Create your models here.

class Pelicula(models.Model):
	titulo = models.CharField(max_length=150)
	video = models.URLField(max_length=350, blank=False)
	descripcion = models.TextField()
	año = models.IntegerField()
	director = models.CharField(max_length=150)
	reparto = models.CharField(max_length=200)
	portada = models.URLField(max_length=350, blank=False)
	valoracion = models.FloatField()
	etiqueta = models.CharField(max_length=50)
	

videoclub/apps/pelicula/forms.py
from django import forms
from apps.pelicula.models import Pelicula

class PeliculaForm(forms.ModelForm):
	
	class Meta:
		model = Pelicula
		
		fields = [
			'titulo',
			'video',
			'descripcion',
			'año',
			'director',
			'reparto',
			'portada',
			'valoracion',
			'etiqueta',
		]


		labels={
			'titulo': 'Titulo',
			'video': 'Video',
			'descripcion': 'Descripcion',
			'año':'Año',
			'director':'Director',
			'reparto': 'Reparto',
			'portada':'Portada',
			'valoracion':'Valoracion',
			'etiqueta' : 'Etiqueta'
		}
		
		widgets = {
			'titulo': forms.TextInput(attrs={'class':'form-control'}),
			'video': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion':forms.TextInput(attrs={'class':'form-control'}),
			'año':forms.TextInput(attrs={'class':'form-control'}),
			'director':forms.TextInput(attrs={'class':'form-control'}),
			'portada': forms.TextInput(attrs={'class':'form-control'}),
			'reparto': forms.TextInput(attrs={'class':'form-control'}),
			'valoracion':forms.TextInput(attrs={'class':'form-control'}),
			'etiqueta':forms.TextInput(attrs={'class':'form-control'}),
		}

videoclub/apps/pelicula/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from apps.pelicula.forms import Pelicula, PeliculaForm
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy

# Create your views here.

   
def pelicula_list(request):
	peliculas = Pelicula.objects.all().order_by('titulo')
	return render(request, 'pelicula/listadoPeliculas.html',{'peliculas': peliculas})
	
def pelicula_filtro(request,etiqueta):
	pelicula = Pelicula.objects.filter(etiqueta=etiqueta).order_by('titulo')
	contexto = {'peliculas': pelicula, 'etiqueta':etiqueta}
	return render(request, 'pelicula/pelicula_filtro.html', contexto)

def pelicula_id(request, pk):
    pelicula = get_object_or_404(Pelicula, pk=pk)
    if request.method == 'POST':
    	print(pelicula.valoracion)
    	voto = request.POST['valoracion']
    	print("voto: " + voto)
    	valoracionFinal = mediaValoracion(pelicula.valoracion, int(voto))
    	print(valoracionFinal)
    	pelicula.valoracion = valoracionFinal
    	print(pelicula.valoracion)
    	pelicula.save()
    	return render(request, 'pelicula/pelicula_id.html', {'pelicula': pelicula})
    else:
    	return render(request, 'pelicula/pelicula_id.html', {'pelicula': pelicula})

def mediaValoracion(valoracion, valoracionNew):
	valoracionFinal = (valoracion + valoracionNew)/2
	return "{0:.1f}".format(float(valoracionFinal))

videoclub/templates/pelicula/listadoPeliculas.html
{% extends 'base/base1.html' %}

{% block content %}
<br/>
<br/>
<div class="container">
	{% if peliculas %}
	<div class="row">
	
    {% for pelicula in peliculas %}
     
     <div class="col-md-3 text-center">
		 <img class="img-responsive center-block" src="{{ pelicula.portada }}" style="width:100%">
		<h5><a href="{% url 'pelicula:pelicula_id' pk=pelicula.pk %}"><p style="font-family:Calibri (Cuerpo); font-size:13px; color:#85C1E9">{{ pelicula.titulo }}</p></a></h5>
	<br/>
	<br/>
    </div>
			
      	
        
    {% endfor %}
    </div>
    {% else %}
		<h1>No hay registros de peliculas</h1>
    {% endif %}
</div>
{% endblock %}

videoclub/templates/pelicula/pelicula_confirm_delete.html
{% extends 'base/base2.html' %}

{% block content %}

<div class="container">
    <div class="center jumbotron text-center" style="background-color: #FFFFFF" > 
		<form method="post">
		{% csrf_token %}
   			 <h4 style="font-family:Chalkboard SE">¿Estás seguro que deseas borrar la película: "{{ pelicula.titulo }}"?</h4>
   			 <p><button type="submit" class="btn btn-warning">SI </button></p>
		</form>
		<p><a class="btn btn-info" href="{% url 'administracion:list' %}" role="button">NO</a></p>
	</div>
</div>
{% endblock %}

videoclub/templates/pelicula/pelicula_detail.html
{% extends 'base/base2.html' %}

{% block content %}
 <div class="container-fluid">
  		<div class="row">
		<div class="col-md-10 col-md-offset-1">
        	<div class="col-md-2">
        		<img class="img-rounded center" src="{{ pelicula.portada }}" width="250px">                                                         
			</div>
			<div class="col-md-8 col-md-offset-1">
				<p style="font-family:Arial; font-size:26px; color:#FFCC80"><strong>{{ pelicula.titulo }}</strong></p>				
				<p style="font-family:Calibri (Cuerpo); font-size:20px; color:#85C1E9"><strong> Valoración</strong>
				<span style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1">{{ pelicula.valoracion }}</span></p> 	
				<p style="font-family:Arial; font-size:14px; color:#17202A"><strong>Año:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:11pt; color:#FFF">{{ pelicula.año }}</p> 
				<p style="font-family:Arial; font-size:14px; color:#17202A"><strong>Director:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:11pt; color:#FFF"> {{ pelicula.director }}</p>  
				<p style="font-family:Arial; font-size:14px; color:#17202A"><strong>Reparto:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:11pt; color:#FFF"> {{ pelicula.reparto }}</p>               	
				<p style="font-family:Arial; font-size:14px; color:#17202A"><strong>Descripción:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:11pt; color:#FFF"> {{ pelicula.descripcion }}</p>
				<iframe width="560" height="315" src="{{ pelicula.video }}" frameborder="0" allowfullscreen></iframe>
				<br>
				<br>
				<br>
				<div class="col-sm-1.5 col-sm-offset-4">
					<p><a class="btn btn-warning btn-lg" href="{% url 'administracion:list' %}" role="button">Atrás</a></p>
				</div>
			</div>
		</div>
		</div>
 	</div> 
  
{% endblock %}

videoclub/templates/pelicula/pelicula_filtro.html
{% extends 'base/base1.html' %}


{% block content %}
	{% if peliculas %}
    <div class="container-fluid">
		<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center">
			<br>
			<br>
			<p><span class="border-bottom" style="font-family:fantasy; font-size:56px; color:#FBFCFC"><strong>{{ etiqueta }}</strong></span></p>
			{% for pelicula in peliculas %}
        	<div class="col-sm-3 text-center">
        		<img src="{{ pelicula.portada }}" class="img-responsive center-block"  width="220">
        		<h5><a href="{% url 'pelicula:pelicula_id' pk=pelicula.pk %}"><span style="font-family:Calibri (Cuerpo); font-size:16px; color:#85C1E9">{{ pelicula.titulo }}</span></a></h5>      
			<br/>
			<br/>                                      
			</div>
			
			
			{% endfor %}
		</div>
		</div>
		
	</div>
    
    {% else %}
		<h1>No hay registros de peliculas</h1>
    {% endif %}
{% endblock %}

videoclub/templates/pelicula/pelicula_form.html
{% extends 'base/base2.html' %}

{% block content %}
<div class="container">
	<div class="jumbotron text-center" style="background-color:#FFFFFF" > 
		<form method="post">
		{% csrf_token %}
		<div class = "row">
			<div class="form-group text-center">
			{{form.as_p}}
			</div>
		</div>
		<p><button type="submit" class="btn btn-info btn-lg">Guardar</button></p>
		</form>
		<p><a class="btn btn-warning btn-lg" href="{% url 'administracion:list' %}" role="button">Atrás</a></p>
		
	</div>
</div>
{% endblock %}

videoclub/templates/pelicula/pelicula_id.html
{% extends 'base/base1.html' %}


{% block content %}
    <div class="container-fluid">
  		<div class="row">
		<div class="col-md-10 col-md-offset-1">
		<br>
		<br>
		<br>
		<br>
        	<div class="col-md-3">
        		<img class="img-rounded center" src="{{ pelicula.portada }}" width="350px">                                                         
			</div>
			<div class="col-md-6 col-md-offset-1">
				
				<p style="font-family:Marker Felt; font-size:50px; color:#131D29"><strong>{{ pelicula.titulo }}</strong></p>	
				<div class="estrellas">
				<form role="form" method="post" id='form_votar'>
				{% csrf_token %}
					<p style="font-family:Calibri (Cuerpo); font-size:20px; color:#85C1E9"><strong> Valoración</strong>
					<span style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1">{{ pelicula.valoracion }}</span></p> 
					<p class="clasificacion">
						<input id="voto1" type="submit" name="valoracion" value="5" ><label for="voto1">&#9733;</label>
    					<input id="voto2" type="submit" name="valoracion" value="4"><label for="voto2">&#9733;</label>
	    				<input id="voto3" type="submit" name="valoracion" value="3"><label for="voto3">&#9733;</label>
	    				<input id="voto4" type="submit" name="valoracion" value="2"><label for="voto4">&#9733;</label>
						<input id="voto5" type="submit" name="valoracion" value="1"><label for="voto5">&#9733;</label>	
					</p> 			
	  		 	</form>

	  		 	
	  		  </div>
	  		 	
				<a class="btn btn-info btn-lg" href="{{ pelicula.video }}" role="button"><strong>Ver Película</strong></a>
				<br>
				<br>
				<p style="font-family:Arial; font-size:18px; color:#17202A"><strong>Año:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1">{{ pelicula.año }}</p> 
				<p style="font-family:Arial; font-size:18px; color:#17202A"><strong>Director:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1"> {{ pelicula.director }}</p>  
				<p style="font-family:Arial; font-size:18px; color:#17202A"><strong>Reparto:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1"> {{ pelicula.reparto }}</p>               	
				<p style="font-family:Arial; font-size:18px; color:#17202A"><strong>Descripción:</strong></p><p style="font-family:Calibri (Cuerpo); font-size:12pt; color:#D4E6F1"> {{ pelicula.descripcion }}</p>
				
			</div>
		</div>
		</div>
 	</div> 
  
{% endblock %}

videoclub/templates/pelicula/pelicula_list.html
{% extends 'base/base2.html' %}

{% block content %}
<div class="col-md-8 col-md-offset-2" style="text-align:center">
		<a class="btn btn-info btn-lg" href="{% url 'administracion:new' %}" role="button"><strong>Añadir Película</strong></a>
		<br/>
		<br/>
		<br/>
		<table class="table table-hover">
		  <thead>
		    <tr>
		     
		      <th scope="col"><strong><p  style="font-size:12pt; color:#000; text-align:center">Película</strong></p></th>
		      <th scope="col"><strong><p  style="font-size:12pt; color:#000; text-align:center">Editar</strong></p></th>
		      <th scope="col"><strong><p  style="font-size:12pt; color:#000; text-align:center">Eliminar</strong></p></th>
		    </tr>
		  </thead>
		  {% for pelicula in object_list %}
		  <tbody>
		    <tr>
		      <td><strong><p  style="font-size:12pt;"><a href="{% url 'administracion:detail' pelicula.id %}">{{ pelicula.titulo }}</a></strong></p></td>
		      <td><a href="{% url 'administracion:edit' pelicula.id %}"><img src="https://cdn4.iconfinder.com/data/icons/project-document-std-pack-3/512/edit_tasks-512.png" width="20px"></a></td>
		      <td><a href="{% url 'administracion:delete' pelicula.id %}"><img class="aligncenter" src="https://docs.qgis.org/2.14/es/_images/mActionDeleteSelected.png" width="20px"></a></td>
		    </tr>
		  </tbody>
		{% endfor %}
		</table>
		<div class="col-sm-1.5">
			<br>
			<br>
			<p><a class="btn btn-warning btn-lg" href="{% url 'administracion:admin' %}" role="button">Atrás</a></p>
		</div>
		</div> 
	</div>
{% endblock %}