videoclub/apps/administracion/urls.py
from django.conf.urls import patterns, url 
from apps.administracion.views import Administracion, PeliculaList, PeliculaDetail, PeliculaCreation, PeliculaUpdate, PeliculaDelete, UsuarioList, UsuarioDetail, UsuarioCreation, UsuarioUpdate, UsuarioDelete



urlpatterns= patterns('',
	url(r'^$', Administracion.as_view(),name='admin'),
   
    url(r'^pelicula/$', PeliculaList.as_view(), name='list'),
    url(r'^pelicula/(?P<pk>\d+)$', PeliculaDetail.as_view(), name='detail'),
    url(r'^pelicula/nuevo$', PeliculaCreation.as_view(), name='new'),
    url(r'^pelicula/editar/(?P<pk>\d+)$', PeliculaUpdate.as_view(), name='edit'),
    url(r'^pelicula/borrar/(?P<pk>\d+)$', PeliculaDelete.as_view(), name='delete'),  
    
    url(r'^usr/$', UsuarioList.as_view(), name='listUsr'),
    url(r'^usr/(?P<pk>\d+)$', UsuarioDetail.as_view(), name='detailUsr'),
    url(r'^usr/nuevo$', UsuarioCreation.as_view(), name='newUsr'),
    url(r'^usr/editar/(?P<pk>\d+)$', UsuarioUpdate.as_view(), name='editUsr'),
    url(r'^usr/borrar/(?P<pk>\d+)$', UsuarioDelete.as_view(), name='deleteUsr'),
)


    

videoclub/apps/pagVideoclub/urls.py
from django.conf.urls import patterns, url
from .views import Logout, peliculas, search

urlpatterns= patterns('',
	url(r'^$', peliculas, name='videoclub'),
	url(r'^search', search, name='search'),
	url(r'^salir', Logout.as_view(), name='logout'),
	
)

videoclub/videoclub/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from .views import login_view

urlpatterns = [
  	url(r'^$', login_view, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administracion/', include('apps.administracion.urls', namespace='administracion')),
    url(r'^usuario/', include('apps.usuario.urls', namespace='usuario')),
    url(r'^pelicula/', include('apps.pelicula.urls', namespace='pelicula')),
    url(r'^videoclub/', include('apps.pagVideoclub.urls', namespace='pagVideoclub')),  
    url(r'^reset/reseteoContraseña', password_reset, {'template_name':'resetearContraseña/reseteoPwdForm.html','email_template_name':'resetearContraseña/reseteoPwdEmail.html'}, name='password_reset'),
   	url(r'^reset/reseteoAvisoContraseña', password_reset_done, {'template_name':'resetearContraseña/reseteoPwdAviso.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'resetearContraseña/reseteoPwdConfir.html'}, name='password_reset_confirm'),
	url(r'^reset/reseteo', password_reset_complete, {'template_name':'resetearContraseña/reseteoPwd.html'}, name='password_reset_complete'),

]

videoclub/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">	
	<head>
        <title>{% block title %} VideoClub DAW {% endblock %} </title>
        <meta charset="utf-8">
   		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
   		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
 	    <meta name="description" content="Practica Web">
   	 	<meta name="author" content="Maria Ramirez y Nuria Gutierrez">
        
   		<!-- Custom styles -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   		<link rel="stylesheet" href="{% static 'css/estilo1.css' %}">
	  
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
		<!-- Scrip: Inicio de Sesión -->

    </head>

	<body>
		 {% block header %} 
		 
		 {% endblock %}

		{% block content %} 
 		{% endblock %}
 	
 		{% block footer %} 
 		<hr aline="center" size="4" width="600" color="#95A5A6"/>
		<div class="container text-center">
			<span style="font-family:Arial Body; font-size:16px; color:#95A5A6">Universidad Politécnica de Madrid<p>2017-2018</p></span>
		</div>
		
		{% endblock %}
	</body>
</html>

videoclub/templates/base/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">	
	<head>
        <title>{% block title %} VideoClub DAW {% endblock %} </title>
        <meta charset="utf-8">
   		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
   		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
 	    <meta name="description" content="Practica Web">
   	 	<meta name="author" content="Maria Ramirez y Nuria Gutierrez">
        
   		<!-- Custom styles -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   		<link rel="stylesheet" href="{% static 'css/estilo2.css' %}">
	  
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
		<!-- Scrip: Inicio de Sesión -->

   </head>

   <body>

 {% block header %} 
 <div class="container-fluid">
	 <nav class="navbar navbar-inverse">
	   <div class="container-fluid">
	    <ul class="nav navbar-nav">
	       <li class="navbar-left"><a data-toggle="modal" data-target="#myModal1">Ayuda</a></li>      
	    </ul>
	     <ul class="nav navbar-nav">
	       <li class="navbar-left"><button type="button" class="btn btn-default navbar-btn"><a href="{% url 'pagVideoclub:videoclub' %}">Inicio</a></li>      
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	      {% if  user.get_username == "admin"  %}
		  <li><button type="button" class="btn btn-default navbar-btn"><a href="{% url 'administracion:admin' %}">Administración</a></button></li>
		  {% endif %}
	      <li><a><span class="glyphicon glyphicon-user"></span> Hola, {{ user.get_username }}</a></li>
	      <li><a href="{% url 'pagVideoclub:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Cerrar Sesión</a></li>
	    </ul>
	  </div>
	</nav>
	<div class="modal fade" class="modal-dialog" id="myModal1" role="dialog">
	  <div class="modal-dialog">
	     <div class="modal-content text-center" ">
	 		 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			 <span aria-hidden="true">&times;</span></button>
			 <p><h4 style="color:#1ABC9C">¿Necesitas ayuda?</h4></p>
			 <p style="font-size:12pt">Para cualquier consulta escribe a <strong>practicanym@gmail.com</strong>, ¡estaremos encantadas de ayudarte!</p>						  
			 
		</div>
	  </div>
    </div>
   </div>

	
	<div class="container">
	  <div class="row" align="center">
        <div class="col-md-8" align="right"><p  style="font-size:60pt; font-family:Chalkduster; color:black">Daw Movie</p></p></div>
        <div class="col-md-4"  align="left"><img class="alignright" src="https://icon-icons.com/icons2/810/PNG/512/cinema_popcorn_icon-icons.com_66128.png" width="100px"></div>
      </div>
	  <div class="row" align="center">
		<div class="col-md-12">
		<form id="searchform" action="{% url 'pagVideoclub:search' %}" method="get">
		   <ul class="input-group col-md-6">
		  	 <input class="form-control" id="searchbox" name="titulo" type="text" placeholder="Buscar" aria-label="Buscar">
		  	 <span class="input-group-btn"><button class="btn btn-info btn-md" type="searchbutton" "><i class="glyphicon glyphicon-search"></i></button></span>
		   </ul>
		</form>
		 </div>
	   </div>
	</div>
	{% endblock %}
	
		{% block content %} 
 		{% endblock %}
 	
 		{% block footer %} 
 		<hr aline="center" size="4" width="600" color="#95A5A6"/>
		<div class="container text-center">
			<span style="font-family:Calibri (Cuerpo); font-size:14px; color:#000">Universidad Politécnica de Madrid
			<p>2017-2018</p></span>
		</div>
		
		{% endblock %}
	</body>
</html>

videoclub/templates/base/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">	
	<head>
        <title>{% block title %} VideoClub DAW {% endblock %} </title>
        <meta charset="utf-8">
   		<meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
   		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
 	    <meta name="description" content="Practica Web">
   	 	<meta name="author" content="Maria Ramirez y Nuria Gutierrez">
        
   		<!-- Custom styles -->
   		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   		<link rel="stylesheet" href="{% static 'css/css1.css' %}">
	  
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		
		<!-- Scrip: Inicio de Sesión -->

   </head>

<body>

 {% block header %} 

<div class="container-fluid">
	 <nav class="navbar navbar-inverse">
	   <div class="container-fluid">
	    <ul class="nav navbar-nav">
	       <li class="navbar-left"><a href="{% url 'pagVideoclub:videoclub' %}">Inicio</a></li>      
	    </ul>
	   <ul class="nav navbar-nav navbar-right">
	      <li><a><span class="glyphicon glyphicon-user"></span> Hola, {{ user.get_username }}</a></li>
	      <li><a href="{% url 'pagVideoclub:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Cerrar Sesión</a></li>
	   </ul>
	  </div>
	</nav>
	 <br/>
	<div class="container text-center">
	  <div class="row">
        <div class="col-md-9" align="right"><p  style="font-size:60pt; font-family:Chalkduster; color:black">Administración</p></div>
        <div class="col-md-3"  align="left"><img class="alignright" src="https://content.mycutegraphics.com/graphics/movie/directors-chair-popcorn-drink.png" width="125px"></div>
      </div>
	  <br/>
	  <br/>
	 
	</div>
		{% endblock %}
	
		{% block content %} 
 		{% endblock %}
 	
 		{% block footer %} 
 		<hr aline="center" size="4" width="600" color="#95A5A6"/>
		<div class="container text-center">
			<span style="font-family:Calibri (Cuerpo); font-size:14px; color:#000">Universidad Politécnica de Madrid
			<p>2017-2018</p></span>
		</div>
		
		{% endblock %}
</body>
</html>